use std::collections::HashMap;
use std::fs::File;
use std::io::{self, Write};
use std::net::IpAddr;
use std::time::Instant;

use crate::dao::SqliteDB;

/// Output format types compatible with nmap
#[derive(Debug, Clone, PartialEq)]
pub enum OutputFormat {
    /// Normal output (-oN): Human-readable text format
    Normal,
    /// Grepable output (-oG): One line per host, parseable
    Grepable,
    /// XML output (-oX): Nmap XML DTD compliant
    Xml,
    /// JSON output (-oJ): Machine-readable JSON
    Json,
    /// All formats (-oA): Generate all of the above
    All,
}

impl OutputFormat {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "normal" | "n" => OutputFormat::Normal,
            "grepable" | "g" => OutputFormat::Grepable,
            "xml" | "x" => OutputFormat::Xml,
            "json" | "j" => OutputFormat::Json,
            "all" | "a" => OutputFormat::All,
            _ => OutputFormat::Normal,
        }
    }

    pub fn extension(&self) -> &str {
        match self {
            OutputFormat::Normal => ".nmap",
            OutputFormat::Grepable => ".gnmap",
            OutputFormat::Xml => ".xml",
            OutputFormat::Json => ".json",
            OutputFormat::All => ".all",
        }
    }
}

/// Simplified scan result for output formatting
#[derive(Debug, Clone)]
pub struct OutputScanResult {
    pub ip: String,
    pub port: u16,
    pub open: bool,
    pub service: Option<String>,
}

/// Formats scan results in various nmap-compatible output formats
pub struct OutputFormatter {
    scan_start: Instant,
    scan_args: String,
    scan_version: String,
}

impl OutputFormatter {
    pub fn new(scan_args: &str, scan_version: &str) -> Self {
        OutputFormatter {
            scan_start: Instant::now(),
            scan_args: scan_args.to_string(),
            scan_version: scan_version.to_string(),
        }
    }

    pub fn elapsed(&self) -> f64 {
        self.scan_start.elapsed().as_secs_f64()
    }

    /// Write scan results to file(s) in the specified format(s)
    pub fn write_results(
        &self,
        db: &SqliteDB,
        output_base: &str,
        formats: &[OutputFormat],
    ) -> io::Result<()> {
        for format in formats {
            match format {
                OutputFormat::All => {
                    self.write_format(db, output_base, &OutputFormat::Normal)?;
                    self.write_format(db, output_base, &OutputFormat::Grepable)?;
                    self.write_format(db, output_base, &OutputFormat::Xml)?;
                    self.write_format(db, output_base, &OutputFormat::Json)?;
                }
                other => {
                    self.write_format(db, output_base, other)?;
                }
            }
        }
        Ok(())
    }

    fn write_format(
        &self,
        db: &SqliteDB,
        output_base: &str,
        format: &OutputFormat,
    ) -> io::Result<()> {
        let path = format!("{}{}", output_base, format.extension());
        let mut file = File::create(&path)?;
        match format {
            OutputFormat::Normal => self.write_normal(db, &mut file),
            OutputFormat::Grepable => self.write_grepable(db, &mut file),
            OutputFormat::Xml => self.write_xml(db, &mut file),
            OutputFormat::Json => self.write_json(db, &mut file),
            OutputFormat::All => Ok(()),
        }
    }

    /// Get all results from database (with service info enriched)
    fn get_all_results(&self, db: &SqliteDB) -> Vec<OutputScanResult> {
        let mut results = Vec::new();

        // Get scan results (open ports)
        if let Ok((details, _total)) = db.get_scan_results(0, 100000, None, None, None, None) {
            for detail in &details {
                let ip = detail.ip_address.clone();
                let port = detail.port;

                // Try to get service info for this IP
                let service = db.get_service_info_by_ip(&ip).ok().and_then(|infos| {
                    infos
                        .into_iter()
                        .find(|info| info.port == port)
                        .map(|info| info.service_name)
                });

                results.push(OutputScanResult {
                    ip,
                    port,
                    open: true,
                    service,
                });
            }
        }

        results
    }

    /// Write normal output (like -oN)
    pub fn write_normal(&self, db: &SqliteDB, out: &mut dyn Write) -> io::Result<()> {
        writeln!(
            out,
            "# Nmap scan report generated by ip-scan {}",
            self.scan_version
        )?;
        writeln!(
            out,
            "# Date: {}",
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S")
        )?;
        writeln!(out, "# Args: {}", self.scan_args)?;
        writeln!(out, "# Elapsed: {:.2}s", self.elapsed())?;
        writeln!(out, "#")?;
        writeln!(out)?;

        let results = self.get_all_results(db);
        let grouped = self.group_by_ip(&results);

        for (ip, ports) in &grouped {
            writeln!(out, "Starting Nmap scan report for {}", ip)?;

            let open_ports: Vec<&OutputScanResult> = ports.iter().filter(|p| p.open).collect();
            let closed_ports: Vec<&OutputScanResult> = ports.iter().filter(|p| !p.open).collect();

            if !open_ports.is_empty() {
                writeln!(out, "Host {} is up ({:.2}s latency).", ip, 0.0)?;
                writeln!(out, "Not shown: {} closed ports", closed_ports.len())?;
                writeln!(out, "PORT      STATE SERVICE")?;

                for port in open_ports {
                    let service = port.service.as_deref().unwrap_or("unknown");
                    writeln!(out, "{:<8} open  {}", port.port, service)?;
                }
            } else {
                writeln!(out, "Host {} is down (0% loss).", ip)?;
            }

            writeln!(
                out,
                "Nmap done: 1 IP address ({:.2}s elapsed)",
                self.elapsed()
            )?;
            writeln!(out)?;
        }

        Ok(())
    }

    /// Write grepable output (like -oG)
    pub fn write_grepable(&self, db: &SqliteDB, out: &mut dyn Write) -> io::Result<()> {
        writeln!(
            out,
            "# Nmap grepable output generated by ip-scan {}",
            self.scan_version
        )?;
        writeln!(
            out,
            "# Date: {}",
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S")
        )?;
        writeln!(out, "# Args: {}", self.scan_args)?;
        writeln!(out, "# Elapsed: {:.2}s", self.elapsed())?;
        writeln!(out)?;

        let results = self.get_all_results(db);
        let grouped = self.group_by_ip(&results);

        for (ip, ports) in &grouped {
            let open_ports: Vec<&OutputScanResult> = ports.iter().filter(|p| p.open).collect();

            let host_status = if open_ports.is_empty() { "Down" } else { "Up" };
            writeln!(out, "Host: {} Status: {}", ip, host_status)?;

            if !open_ports.is_empty() {
                let port_strs: Vec<String> = open_ports
                    .iter()
                    .map(|p| {
                        let service = p.service.as_deref().unwrap_or("unknown");
                        format!("{}/tcp//{}//", p.port, service)
                    })
                    .collect();
                writeln!(out, "Ports: {}", port_strs.join(","))?;
            }
        }

        Ok(())
    }

    /// Write XML output (like -oX)
    pub fn write_xml(&self, db: &SqliteDB, out: &mut dyn Write) -> io::Result<()> {
        writeln!(out, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>")?;
        writeln!(
            out,
            "<?xml-stylesheet href=\"file:///usr/share/nmap/nmap.xsl\" type=\"text/xsl\"?>"
        )?;
        writeln!(out)?;
        writeln!(out, "<!DOCTYPE nmaprun PUBLIC \"-//IDN nmap.org//DTD Nmap XML 1.04//EN\" \"https://svn.nmap.org/nmap/docs/nmaprun.dtd\">")?;
        writeln!(out)?;
        writeln!(
            out,
            "<nmaprun scanner=\"ip-scan\" version=\"{}\" start=\"{}\" startstr=\"{}\">",
            self.scan_version,
            chrono::Local::now().timestamp(),
            chrono::Local::now().format("%b %d %H:%M:%S %Y")
        )?;

        writeln!(out, "  <scaninfo protocol=\"tcp\" numservices=\"1000\"/>")?;
        writeln!(out, "  <verbose level=\"0\"/>")?;
        writeln!(out, "  <debug level=\"0\"/>")?;
        writeln!(out)?;

        let results = self.get_all_results(db);
        let grouped = self.group_by_ip(&results);

        for (ip, ports) in &grouped {
            writeln!(
                out,
                "  <host starttime=\"0\" endtime=\"{}\">",
                self.elapsed() as i64
            )?;
            writeln!(
                out,
                "    <status state=\"{}\" reason=\"user-set\" reason_ttl=\"0\"/>",
                if ports.iter().any(|p| p.open) {
                    "up"
                } else {
                    "down"
                }
            )?;
            writeln!(out, "    <address addr=\"{}\" addrtype=\"ipv4\"/>", ip)?;

            writeln!(out, "    <ports>")?;
            for port in ports {
                let state = if port.open { "open" } else { "closed" };
                let service = port.service.as_deref().unwrap_or("unknown");
                writeln!(
                    out,
                    "      <port protocol=\"tcp\" portid=\"{}\">",
                    port.port
                )?;
                writeln!(
                    out,
                    "        <state state=\"{}\" reason=\"syn-ack\" reason_ttl=\"64\"/>",
                    state
                )?;
                writeln!(
                    out,
                    "        <service name=\"{}\" method=\"table\" conf=\"3\"/>",
                    service
                )?;
                writeln!(out, "      </port>")?;
            }
            writeln!(out, "    </ports>")?;
            writeln!(out, "  </host>")?;
        }

        writeln!(out)?;
        writeln!(out, "  <runstats>")?;
        writeln!(
            out,
            "    <finished timestr=\"{}\" elapsed=\"{:.2}\" />",
            chrono::Local::now().format("%b %d %H:%M:%S %Y"),
            self.elapsed()
        )?;
        writeln!(
            out,
            "    <hosts total=\"{}\" up=\"{}\" down=\"{}\"/>",
            grouped.len(),
            grouped
                .values()
                .filter(|p| p.iter().any(|r| r.open))
                .count(),
            grouped
                .values()
                .filter(|p| !p.iter().any(|r| r.open))
                .count()
        )?;
        writeln!(out, "  </runstats>")?;
        writeln!(out, "</nmaprun>")?;

        Ok(())
    }

    /// Write JSON output
    pub fn write_json(&self, db: &SqliteDB, out: &mut dyn Write) -> io::Result<()> {
        let results = self.get_all_results(db);
        let grouped = self.group_by_ip(&results);

        let mut output = serde_json::json!({
            "scanner": "ip-scan",
            "version": self.scan_version,
            "args": self.scan_args,
            "elapsed": self.elapsed(),
            "start_time": chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
            "hosts": grouped.iter().map(|(ip, ports)| {
                let open_ports: Vec<&OutputScanResult> = ports.iter().filter(|p| p.open).collect();
                serde_json::json!({
                    "ip": ip.to_string(),
                    "status": if open_ports.is_empty() { "down" } else { "up" },
                    "open_ports": open_ports.iter().map(|p| {
                        serde_json::json!({
                            "port": p.port,
                            "state": "open",
                            "service": p.service.as_deref().unwrap_or("unknown"),
                        })
                    }).collect::<Vec<_>>(),
                    "total_open": open_ports.len(),
                    "total_closed": ports.len() - open_ports.len(),
                })
            }).collect::<Vec<_>>(),
        });

        serde_json::to_writer_pretty(out, &output)?;
        Ok(())
    }

    /// Group scan results by IP
    fn group_by_ip(&self, results: &[OutputScanResult]) -> HashMap<IpAddr, Vec<OutputScanResult>> {
        let mut grouped: HashMap<IpAddr, Vec<OutputScanResult>> = HashMap::new();
        for result in results {
            if let Ok(ip) = result.ip.parse::<IpAddr>() {
                grouped.entry(ip).or_default().push(result.clone());
            }
        }
        grouped
    }
}

/// Parse nmap-style output flags (-oN, -oX, -oG, -oJ, -oA)
pub fn parse_output_flags(flags: &[String]) -> (Option<String>, Vec<OutputFormat>) {
    let mut output_base: Option<String> = None;
    let mut formats: Vec<OutputFormat> = Vec::new();

    let mut i = 0;
    while i < flags.len() {
        match flags[i].as_str() {
            "-oN" | "-oX" | "-oG" | "-oJ" | "-oA" => {
                if i + 1 < flags.len() {
                    output_base = Some(flags[i + 1].clone());
                    let fmt = match flags[i].as_str() {
                        "-oN" => OutputFormat::Normal,
                        "-oX" => OutputFormat::Xml,
                        "-oG" => OutputFormat::Grepable,
                        "-oJ" => OutputFormat::Json,
                        "-oA" => OutputFormat::All,
                        _ => unreachable!(),
                    };
                    formats.push(fmt);
                    i += 2;
                }
            }
            "-o" => {
                // Generic output: -o <format> <base>
                if i + 2 < flags.len() {
                    let fmt = OutputFormat::from_str(&flags[i + 1]);
                    output_base = Some(flags[i + 2].clone());
                    formats.push(fmt);
                    i += 3;
                }
            }
            _ => i += 1,
        }
    }

    (output_base, formats)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_output_format_from_str() {
        assert_eq!(OutputFormat::from_str("normal"), OutputFormat::Normal);
        assert_eq!(OutputFormat::from_str("n"), OutputFormat::Normal);
        assert_eq!(OutputFormat::from_str("grepable"), OutputFormat::Grepable);
        assert_eq!(OutputFormat::from_str("g"), OutputFormat::Grepable);
        assert_eq!(OutputFormat::from_str("xml"), OutputFormat::Xml);
        assert_eq!(OutputFormat::from_str("json"), OutputFormat::Json);
        assert_eq!(OutputFormat::from_str("all"), OutputFormat::All);
    }

    #[test]
    fn test_parse_output_flags() {
        let flags = vec!["-oN".to_string(), "output".to_string()];
        let (base, formats) = parse_output_flags(&flags);
        assert_eq!(base, Some("output".to_string()));
        assert_eq!(formats, vec![OutputFormat::Normal]);

        let flags = vec!["-oA".to_string(), "scan".to_string()];
        let (base, formats) = parse_output_flags(&flags);
        assert_eq!(base, Some("scan".to_string()));
        assert_eq!(formats, vec![OutputFormat::All]);
    }

    #[test]
    fn test_format_extensions() {
        assert_eq!(OutputFormat::Normal.extension(), ".nmap");
        assert_eq!(OutputFormat::Grepable.extension(), ".gnmap");
        assert_eq!(OutputFormat::Xml.extension(), ".xml");
        assert_eq!(OutputFormat::Json.extension(), ".json");
    }
}
