const API='/api/v1';
const PORT_COLORS=['#6de4ff','#6b83ff','#48e0a7','#ffc56d','#ff718a','#a47cff','#e77dff','#48b5e0'];
const S={page:1,pageSize:50,searchDebounce:null,prevTotal:0,prevTime:Date.now(),scanRate:0,results:[],services:[],map:null};
document.addEventListener('DOMContentLoaded',()=>{refreshAll();setInterval(pollStatus,2000);setInterval(pollRate,3000);setInterval(updateClock,1000);updateClock();});
function $(id){return document.getElementById(id)}
function toast(msg,type='info',ms=3500){const el=document.createElement('div');el.className='toast toast-'+type;el.textContent=msg;$('toast-box').appendChild(el);setTimeout(()=>el.remove(),ms)}
async function api(path,opts){const r=await fetch(API+path,opts);if(r.ok)return r.json();throw Error(await r.text())}
function updateClock(){$('clock').textContent=new Date().toLocaleTimeString('en-GB',{hour12:false})}
function switchTab(id,btn){document.querySelectorAll('.tab-pane').forEach(p=>p.style.display='none');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));$('tab-'+id).style.display='';if(btn)btn.classList.add('active');if(id==='history')fetchHistory();if(id==='map'){if(!S.map)setupMap();renderMap()}}
async function refreshAll(){await Promise.all([fetchStats(),fetchResults(1),fetchServices(),pollStatus()]);$('freshness').textContent='LIVE';}
async function fetchStats(){try{const d=await api('/stats');$('s-total').textContent=d.total_open_records||0;$('s-unique').textContent=d.unique_ips||0;S.prevTotal=d.total_open_records||0;const tp=await api('/stats/top-ports?limit=10');if(tp.ports?.length){$('s-topport').textContent=`${tp.ports[0].port} · ${tp.ports[0].open_count}`;renderPortBar(tp.ports,tp.total_open_ports)} }catch(e){console.warn(e)}}
function renderPortBar(ports,total){if(!total){$('port-bar').innerHTML='';$('port-legend').innerHTML='';$('chart-empty').style.display='block';return}$('chart-empty').style.display='none';$('port-bar').innerHTML=ports.slice(0,8).map((p,i)=>`<div class="port-bar-seg" style="width:${p.open_count/total*100}%;background:${PORT_COLORS[i]}" title="${p.port}: ${p.open_count}"></div>`).join('');$('port-legend').innerHTML=ports.slice(0,8).map((p,i)=>`<span class="port-legend-item"><i class="port-legend-dot" style="background:${PORT_COLORS[i]}"></i>${p.port} (${(p.open_count/total*100).toFixed(1)}%)</span>`).join('')}
async function fetchServices(){try{const d=await api('/services?page=1&page_size=500');S.services=d.summaries||[];if(S.map)renderMap()}catch(e){S.services=[]}}
async function pollStatus(){try{const d=await api('/scan/status');const running=d.is_running;const el=$('scan-status');el.className='badge badge-'+(running?'running':(d.status==='Stopped'?'stopped':'idle'));el.textContent=running?'RUNNING':(d.status||'IDLE');$('scan-round').textContent=d.current_round||'—';$('btn-start').disabled=running;$('btn-stop').disabled=!running;$('progress-bar').style.width=running?'68%':'18%'}catch(e){}}
async function pollRate(){try{const d=await api('/stats'),now=Date.now(),dt=(now-S.prevTime)/1000;S.scanRate=dt>0?Math.max(0,Math.round(((d.total_open_records||0)-S.prevTotal)/dt)):0;S.prevTotal=d.total_open_records||0;S.prevTime=now;$('scan-rate').textContent=S.scanRate?S.scanRate+'/s':'—';$('metric-velocity').textContent=S.scanRate?S.scanRate+'/s':'—'}catch(e){}}
async function startScan(){const cfg={target:$('cfg-target').value||null,start_ip:null,end_ip:null,ports:$('cfg-ports').value||null,timeout:parseInt($('cfg-timeout').value)||500,concurrency:parseInt($('cfg-concurrency').value)||500,skip_private:$('cfg-skip-private').checked,syn:false};try{await api('/scan/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});toast('扫描任务已启动','success');setTimeout(refreshAll,700)}catch(e){toast('启动失败: '+e.message,'error')}}
async function stopScan(){try{await api('/scan/stop',{method:'POST'});toast('正在停止扫描','info');setTimeout(refreshAll,700)}catch(e){toast('停止失败: '+e.message,'error')}}
async function fetchResults(page){S.page=page;const tb=$('tb-results');if(!tb)return;tb.innerHTML='<tr><td colspan="6" style="text-align:center;color:#8490aa">同步中…</td></tr>';try{const d=await api(`/results?page=${page}&page_size=${S.pageSize}`);S.results=d.results||[];renderRows(S.results);$('result-count').textContent=`${d.total||0} 条记录`;$('pg-info').textContent=`${d.page} / ${d.total_pages||1}`;$('pg-prev').disabled=d.page<=1;$('pg-next').disabled=d.page>=(d.total_pages||1)}catch(e){tb.innerHTML='<tr><td colspan="6">无法加载结果</td></tr>'}}
function renderRows(items){const q=($('search-input')?.value||'').toLowerCase(),rows=items.filter(r=>!q||[r.ip_address,r.port,r.country,r.city,r.reverse_dns].some(x=>String(x||'').toLowerCase().includes(q)));$('tb-results').innerHTML=rows.length?rows.map(r=>{const rdns=r.reverse_dns||'';const ipCell=rdns?`<span>${r.ip_address||'—'}</span><br><span style="font-size:10px;color:#a47cff">${rdns}</span>`:`${r.ip_address||'—'}`;return`<tr><td>${ipCell}</td><td><span class="tag">${r.port||'—'}</span></td><td>${r.ip_type||'TCP'}</td><td class="geo">${[r.country,r.city].filter(Boolean).join(', ')||'—'}</td><td>${r.scan_round||'—'}</td><td>${r.first_seen?new Date(r.first_seen).toLocaleTimeString():'—'}</td><td style="font-size:11px;color:#8490aa">${rdns?'✓':'—'}</td></tr>`}).join(''):'<tr><td colspan="7" style="text-align:center;color:#8490aa">没有匹配结果</td></tr>'}
function onSearch(){clearTimeout(S.searchDebounce);S.searchDebounce=setTimeout(()=>renderRows(S.results),180)}
function page(d){if(S.page+d>0)fetchResults(S.page+d)}
async function fetchHistory(){const tb=$('tb-history');try{const d=await api('/scan/history');const scans=d.scans||[];tb.innerHTML=scans.length?scans.map(s=>`<tr><td>${s.round||'—'}</td><td>${s.start_time?new Date(s.start_time).toLocaleString():'—'}</td><td>${s.end_time?new Date(s.end_time).toLocaleString():'—'}</td><td><span class="tag">${s.status||'Done'}</span></td><td>${s.total_open_ports||0} open / ${s.ports_scanned||0} scanned</td></tr>`).join(''):'<tr><td colspan="5" style="text-align:center;color:#8490aa">暂无扫描历史</td></tr>'}catch(e){tb.innerHTML='<tr><td colspan="5">无法加载历史</td></tr>'}}
function exportData(fmt){toast(`正在准备 ${fmt.toUpperCase()} 快照…`);window.open(`${API}/export/${fmt}`,'_blank')}
// Lightweight dependency-free 3D constellation renderer.
function setupMap(){const canvas=$('ip-map'),stage=canvas.parentElement,ctx=canvas.getContext('2d');const map={canvas,stage,ctx,nodes:[],rotX:-.18,rotY:.5,zoom:1,drag:false,lastX:0,lastY:0,auto:true};S.map=map;const resize=()=>{const d=devicePixelRatio||1;canvas.width=stage.clientWidth*d;canvas.height=stage.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);map.w=stage.clientWidth;map.h=stage.clientHeight};resize();new ResizeObserver(resize).observe(stage);canvas.addEventListener('pointerdown',e=>{map.drag=true;map.auto=false;map.lastX=e.clientX;map.lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!map.drag)return;map.rotY+=(e.clientX-map.lastX)*.008;map.rotX+=(e.clientY-map.lastY)*.006;map.lastX=e.clientX;map.lastY=e.clientY;});canvas.addEventListener('pointerup',()=>map.drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();map.zoom=Math.max(.55,Math.min(1.8,map.zoom-e.deltaY*.0008))},{passive:false});canvas.addEventListener('click',e=>{const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;const hit=map.nodes.slice().sort((a,b)=>b.z-a.z).find(n=>Math.hypot(n.sx-x,n.sy-y)<Math.max(12,n.r+5));if(hit)showNodeDetail(hit)});function tick(){if(map.auto&&!map.drag)map.rotY+=.0018;drawMap();requestAnimationFrame(tick)}tick()}
function renderMap(){if(!S.map)return;const map=S.map,byIp=new Map();S.results.forEach(r=>{if(!byIp.has(r.ip_address))byIp.set(r.ip_address,{ip:r.ip_address,ports:[],geo:[r.country,r.city].filter(Boolean).join(', ')});byIp.get(r.ip_address).ports.push(r.port)});S.services.forEach(s=>{if(!byIp.has(s.ip))byIp.set(s.ip,{ip:s.ip,ports:[],geo:'',services:s.services||[]});const n=byIp.get(s.ip);n.services=s.services||[];n.ports=[...new Set([...(n.ports||[]),...(s.services||[]).map(x=>x.port).filter(Boolean)])]});const vals=[...byIp.values()].slice(0,180);map.nodes=vals.map((n,i)=>{const phi=Math.acos(1-2*(i+.5)/Math.max(vals.length,1)),theta=Math.PI*(1+Math.sqrt(5))*i;return {...n,x:Math.sin(phi)*Math.cos(theta),y:Math.cos(phi),z:Math.sin(phi)*Math.sin(theta)}});$('map-node-count').textContent=map.nodes.length;$('map-edge-count').textContent=map.nodes.reduce((a,n)=>a+(n.ports?.length||0),0);$('map-empty').style.display=map.nodes.length?'none':'grid'}
function drawMap(){const m=S.map;if(!m||!m.w)return;const c=m.ctx,w=m.w,h=m.h;c.clearRect(0,0,w,h);const glow=c.createRadialGradient(w/2,h/2,10,w/2,h/2,Math.min(w,h)*.48);glow.addColorStop(0,'#284b7930');glow.addColorStop(1,'#09112100');c.fillStyle=glow;c.fillRect(0,0,w,h);const sx=Math.sin(m.rotX),cx=Math.cos(m.rotX),sy=Math.sin(m.rotY),cy=Math.cos(m.rotY);m.nodes.forEach(n=>{let x=n.x*cy-n.z*sy,z=n.x*sy+n.z*cy;let y=n.y*cx-z*sx;z=n.y*sx+z*cx;n.z=z;n.sx=w/2+x* Math.min(w,h)*.34*m.zoom;n.sy=h/2+y*Math.min(w,h)*.34*m.zoom;n.r=(z+1.7)*2.7});m.nodes.forEach((n,i)=>{const next=m.nodes[(i+1)%m.nodes.length];if(i%3!==0||!next)return;c.beginPath();c.moveTo(n.sx,n.sy);c.lineTo(next.sx,next.sy);c.strokeStyle=`rgba(111,129,255,${.05+(n.z+1)/2*.12})`;c.lineWidth=1;c.stroke()});m.nodes.forEach(n=>{const glowR=n.r*4;c.beginPath();c.arc(n.sx,n.sy,glowR,0,Math.PI*2);c.fillStyle=`rgba(109,228,255,${.025+(n.z+1)/2*.06})`;c.fill();c.beginPath();c.arc(n.sx,n.sy,Math.max(2,n.r),0,Math.PI*2);c.fillStyle=n.ports?.length>3?'#a47cff':'#6de4ff';c.shadowBlur=12;c.shadowColor=c.fillStyle;c.fill();c.shadowBlur=0})}
function showNodeDetail(n){$('node-detail').classList.add('open');$('detail-ip').textContent=n.ip;$('detail-meta').textContent=[n.geo,n.ports?.length?`${n.ports.length} 个开放端口`:'' ].filter(Boolean).join(' · ')||'网络节点';$('detail-services').innerHTML=(n.services?.length?n.services.map(s=>`<span class="service-chip">${s.service_name||s.port||'service'}</span>`).join(''):n.ports?.map(p=>`<span class="service-chip">PORT ${p}</span>`).join('')||'<span class="muted">暂无服务详情</span>')}
function closeNodeDetail(){$('node-detail').classList.remove('open')}function resetMap(){if(S.map){S.map.rotX=-.18;S.map.rotY=.5;S.map.zoom=1;S.map.auto=true}}
